---
sessions:
  config:
    root: ~/.dotfiles/
    start_index: 1
    windows:
      - name: Zsh
        command: nvim ~/.dotfiles/.zshrc
      - name: Tmux
        command: nvim ~/.dotfiles/.tmux.conf.local
      - name: symlink
        command: nvim ~/.dotfiles/scripts/symlink.sh
      - name: Zmux
        layout: main-vertical
        panes:
          - command: nvim ~/.config/zmux/config.yaml
          - command: nvim ~/.config/zmux/projects.yaml
          - command: nvim ~/.config/zmux/zig.yaml
        command: nvim ~/.config/42.yaml
      - name: Nvim
        layout: even-horizontal
        panes:
          - command: nvim ~/.dotfiles/nvim/init.lua
          - command: nvim ~/.dotfiles/nvim/lua/custom/plugins/
      - name: Dotfiles
        command: ls
