return {
	-- {
	-- 	"ellisonleao/gruvbox.nvim",
	-- 	priority = 1000,
	-- 	config = function()
	-- 		-- Default options:
	-- 		require("gruvbox").setup({
	-- 			terminal_colors = true, -- add neovim terminal colors
	-- 			undercurl = true,
	-- 			underline = true,
	-- 			bold = true,
	-- 			italic = {
	-- 				strings = true,
	-- 				emphasis = true,
	-- 				comments = true,
	-- 				operators = false,
	-- 				folds = true,
	-- 			},
	-- 			strikethrough = true,
	-- 			invert_selection = false,
	-- 			invert_signs = false,
	-- 			invert_tabline = false,
	-- 			invert_intend_guides = false,
	-- 			inverse = true, -- invert background for search, diffs, statuslines and errors
	-- 			contrast = "hard", -- can be "hard", "soft" or empty string
	-- 			palette_overrides = {},
	-- 			overrides = {},
	-- 			dim_inactive = false,
	-- 			transparent_mode = true,
	-- 		})
	-- 		vim.cmd("colorscheme gruvbox")
	-- 	end,
	-- },
	-- {
	-- 	"zaldih/themery.nvim",
	-- 	lazy = false,
	-- 	config = function()
	-- 		require("themery").setup({
	-- 			themes = vim.fn.getcompletion("", "color"),
	-- 			-- add the config here
	-- 		})
	-- 	end,
	-- },
	-- {
	-- 	"vague2k/huez.nvim",
	-- 	-- if you want registry related features, uncomment this
	-- 	import = "huez-manager.import",
	-- 	branch = "stable",
	-- 	event = "UIEnter",
	-- 	config = function()
	-- 		require("huez").setup({})
	-- 	end,
	-- },
}
